// Database of all 24 Tunisian Governorates and their cities/delegations

export const TUNISIAN_LOCATIONS = {
  'Tunis': [
    'Tunis Ville',
    'La Marsa',
    'Carthage',
    'Sidi Bou Saïd',
    'Le Bardo',
    'La Goulette',
    'Le Kram',
    'El Menzah',
    'El Omrane',
    'El Omrane Supérieur',
    'Bab Souika',
    'Bab El Bhar',
    'Ettahrir',
    'El Kabaria',
    'Sidi El Béchir',
    'Jebel Jelloud',
    'El Ouardia',
    'El Hraïria',
    'Sidi Hassine'
  ],
  'Ariana': [
    'Ariana Ville',
    'La Soukra',
    'Raoued',
    'Mnihla',
    'Ettadhamen',
    'Kalâat el-Andalous',
    'Sidi Thabet'
  ],
  'Ben Arous': [
    'Ben Arous',
    'Hammam Lif',
    'Hammam Chott',
    'Ezzahra',
    'Radès',
    'Mégrine',
    'Mohamedia',
    'Fouchana',
    'Mornag',
    'Bou Mhel el-Bassatine'
  ],
  'Manouba': [
    'Manouba',
    'Dden',
    'Oued Ellil',
    'Tebourba',
    'Djedeida',
    'Mornaguia',
    'El Battan',
    'Borj El Amri'
  ],
  'Nabeul': [
    'Nabeul',
    'Hammamet',
    'Kelibia',
    'Menzel Temime',
    'Korba',
    'Grombalia',
    'Soliman',
    'Dar Chaâbane El Fehri',
    'Béni Khalled',
    'Menzel Bouzelfa',
    'Takelsa',
    'El Haouaria',
    'El Mida',
    'Tazarka'
  ],
  'Bizerte': [
    'Bizerte Nord',
    'Bizerte Sud',
    'Zarzouna',
    'Menzel Bourguiba',
    'Mateur',
    'Ras Jebel',
    'Ghar El Melh',
    'Menzel Jemil',
    'Menzel Abderrahmane',
    'Sejnane',
    'Joumine',
    'Ghezala',
    'Tinja',
    'El Alia'
  ],
  'Zaghouan': [
    'Zaghouan',
    'El Fahs',
    'Bir Mcherga',
    'Zriba',
    'Nadhour',
    'Saouaf'
  ],
  'Béja': [
    'Béja Nord',
    'Béja Sud',
    'Testour',
    'Teboursouk',
    'Medjez el-Bab',
    'Goubellat',
    'Nefza',
    'Amdoun',
    'Thibar'
  ],
  'Jendouba': [
    'Jendouba Ville',
    'Jendouba Nord',
    'Tabarka',
    'Aïn Draham',
    'Bou Salem',
    'Fernana',
    'Ghardimaou',
    'Oued Meliz',
    'Balta-Bou Aouane'
  ],
  'Le Kef': [
    'Le Kef Est',
    'Le Kef Ouest',
    'Dahmani',
    'Tajerouine',
    'Nebeur',
    'Sakiet Sidi Youssef',
    'Sers',
    'Kalaat Senan',
    'Kalaat Khasba',
    'Touiref',
    'El Ksour'
  ],
  'Siliana': [
    'Siliana Nord',
    'Siliana Sud',
    'Bou Arada',
    'Gaâfour',
    'Makthar',
    'Bargou',
    'El Krib',
    'Bourouis',
    'Kesra',
    'Rouhia',
    'Sidi Bou Rouis'
  ],
  'Sousse': [
    'Sousse Ville',
    'Port El Kantaoui',
    'Hammam Sousse',
    'Sousse Riadh',
    'Sousse Jawhara',
    'Sousse Médina',
    'Akouda',
    'Kalâa Kebira',
    'Kalâa Seghira',
    'Msaken',
    'Enfidha',
    'Bouficha',
    'Sidi Bou Ali',
    'Sidi El Hani',
    'Konddar'
  ],
  'Monastir': [
    'Monastir Ville',
    'Ksar Hellal',
    'Moknine',
    'Téboulba',
    'Bekalta',
    'Jemmal',
    'Sahline',
    'Sayada',
    'Lamta',
    'Bouhjar',
    'Ouerdanine',
    'Zéramdine',
    'Béni Hassen'
  ],
  'Mahdia': [
    'Mahdia Ville',
    'Ksour Essef',
    'Chebba',
    'El Jem',
    'Melloulèche',
    'Bou Merdes',
    'Chorbane',
    'Hebira',
    'Essouassi',
    'Sidi Alouane',
    'Ouled Chamekh'
  ],
  'Sfax': [
    'Sfax Ville',
    'Sfax Sud',
    'Sfax Ouest',
    'Sakiet Ezzit',
    'Sakiet Eddaïer',
    'Thyna',
    'El Hencha',
    'Agareb',
    'Jebiniana',
    'Kerkennah',
    'Mahares',
    'Menzel Chaker',
    'Skra',
    'Bir Ali Ben Khalifa'
  ],
  'Kairouan': [
    'Kairouan Nord',
    'Kairouan Sud',
    'Sbikha',
    'Bou Hajla',
    'Haffouz',
    'Oueslatia',
    'Nasrallah',
    'Alaâ',
    'Hadjeb El Ayoun',
    'Chebika',
    'Echrarda'
  ],
  'Kasserine': [
    'Kasserine Nord',
    'Kasserine Sud',
    'Sbeïtla',
    'Thala',
    'Feriana',
    'Haïdra',
    'Foussana',
    'Ezzouhour',
    'Majel Bel Abbès',
    'Jedelienne',
    'El Ayoun'
  ],
  'Sidi Bouzid': [
    'Sidi Bouzid Est',
    'Sidi Bouzid Ouest',
    'Regueb',
    'Meknassy',
    'Jilma',
    'Bir El Hafey',
    'Menzel Bouzaiane',
    'Sidi Ali Ben Aoun',
    'Cebbala Ouled Asker',
    'Ouled Haffouz',
    'Souk Jedid'
  ],
  'Gabès': [
    'Gabès Ville',
    'Gabès Sud',
    'Gabès Ouest',
    'El Hamma',
    'Matmata',
    'Nouvelle Matmata',
    'Mareth',
    'Ghannouch',
    'Métouia',
    'Menzel El Habib'
  ],
  'Médenine': [
    'Médenine Nord',
    'Médenine Sud',
    'Djerba Houmt Souk',
    'Djerba Midoun',
    'Djerba Ajim',
    'Zarzis',
    'Ben Guerdane',
    'Beni Khedache',
    'Sidi Makhlouf'
  ],
  'Tataouine': [
    'Tataouine Nord',
    'Tataouine Sud',
    'Ghomrassen',
    'Remada',
    'Bir Lahmar',
    'Smâr',
    'Dehiba'
  ],
  'Gafsa': [
    'Gafsa Ville',
    'Gafsa Sud',
    'Métlaoui',
    'El Ksar',
    'Redeyef',
    'Moularès',
    'Mdhilla',
    'El Guettar',
    'Sened',
    'Belkhir'
  ],
  'Tozeur': [
    'Tozeur Ville',
    'Nefta',
    'Degache',
    'Tamerza',
    'Hazoua'
  ],
  'Kébili': [
    'Kébili Nord',
    'Kébili Sud',
    'Douz Nord',
    'Douz Sud',
    'Souk Lahad',
    'El Golâa',
    'Faouar'
  ]
};

export const ALL_TUNISIAN_GOVERNORATES = [
  'Toute la Tunisie',
  ...Object.keys(TUNISIAN_LOCATIONS)
];
